name: Teams notify on commits (highlight blocklist changes)

on:
  push:
    branches: [ main ]   # Change if your default branch has a different name

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2   # lets us compare current commit with the previous one

      - name: Notify Teams
        env:
          TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
          ACTOR: ${{ github.actor }}
          COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
        run: |
          FILE="blocked-ips.txt"
          CHANGED="no"
          if git diff --name-only HEAD~1 HEAD 2>/dev/null | grep -qx "$FILE"; then
            CHANGED="yes"
          fi

          if [ "$CHANGED" = "yes" ]; then
            TEXT="🔔 Blocklist changed: $FILE updated in $REPO ($BRANCH) by $ACTOR\n$COMMIT_URL"
          else
            TEXT="ℹ️ Commit to $REPO ($BRANCH) by $ACTOR\n$COMMIT_URL"
          fi

          curl -H "Content-Type: application/json" \
               -d "{\"text\":\"$TEXT\"}" \
               "$TEAMS_WEBHOOK"
